version: '2'
services:

  securetoken:
    image: dtr.avl.dbmi.hms.harvard.edu/dbmi/securetoken:${securetoken_version}
    labels:
      - "app.name=${APPLICATION_NAME}"
      - "app.environment=hackathon"
    restart: always
    expose:
      - 8080
      - 8000
    command: -s/opt/wildfly-swarm/prop.yml
    ports:
      - 8000:8000
    networks:
      - nhanes-net
    volumes:
      - ./properties/prop.yml:/opt/wildfly-swarm/prop.yml:ro

  irct:
    container_name: ${NHANES_IRCT}
    image: dtr.avl.dbmi.hms.harvard.edu/dbmi/irct:${irct_version}
    labels:
      - "app.name=${APPLICATION_NAME}"
      - "app.environment=hackathon"
    depends_on:
       - mysql
    environment:
      - IRCTMYSQLADDRESS=${IRCTMYSQLADDRESS}
      - IRCT_DB_PORT=${IRCT_DB_PORT}
      - IRCT_DB_CONNECTION_USER=${IRCT_DB_CONNECTION_USER}
      - IRCTMYSQLPASS=${IRCTMYSQLPASS}
      - IRCT_SECURITY_SERVICE=http://securetoken:8080/token/validate
    restart: always
    networks:
      - i2b2-net
      - nhanes-net
    expose:
      - 8080

  mysql:
    image: mysql:latest
    labels:
      - "app.name=${APPLICATION_NAME}"
      - "app.environment=hackathon"
    environment:
      - MYSQL_ROOT_PASSWORD=${IRCTMYSQLPASS}
      - MYSQL_DATABASE=irct
    restart: always
    expose:
      - 3306
    networks:
      - nhanes-net

  irct-init:
    image: dtr.avl.dbmi.hms.harvard.edu/dbmi/irct-init:${irct_init_version}
    labels:
      - "app.name=${APPLICATION_NAME}"
      - "app.environment=hackathon"
    depends_on:
      - mysql
      - irct
    environment:
      - IRCT_RESOURCE_NAME=${APPLICATION_NAME}
      - IRCTMYSQLADDRESS=${IRCTMYSQLADDRESS}
      - IRCT_DB_PORT=${IRCT_DB_PORT}
      - IRCT_DB_CONNECTION_USER=${IRCT_DB_CONNECTION_USER}
      - IRCTMYSQLPASS=${IRCTMYSQLPASS}
      - I2B2TRANSMART_URL=${I2B2TRANSMART_URL}
      - SCIDB_HOST=${SCIDB_HOST}
      - SCIDB_USER=${SCIDB_USER}
      - SCIDB_PASSWORD=${SCIDB_PASSWORD}
    volumes:
      - ../script/i2b2tranSMARTsetup.sql:/scratch/irct/sql/i2b2tranSMARTsetup.sql:rw
      - ../script/init-db.sh:/scratch/irct/sql/init-db.sh:rw
    restart: on-failure:10
    networks:
      - nhanes-net

networks:
    nhanes-net:
        external:
            name: projects_nhanes-net
    i2b2-net:
        external:
            name: projects_i2b2-net
