version: '2'
services:


  i2b2transmart:
    image: maxcnunes/docker-url-redirect:latest
    environment:
      - REDIRECT_URL=${I2B2TRANSMART_URL}
    expose:
      - 8080
    networks:
      - nhanes-net

  irct:
    container_name: ${NHANES_IRCT}
    image: dtr.avl.dbmi.hms.harvard.edu/dbmi/irct:${irct_version}
    depends_on:
       - mysql
       - i2b2transmart
    environment:
      - IRCTMYSQLADDRESS=${IRCTMYSQLADDRESS}
      - IRCT_DB_PORT=${IRCT_DB_PORT}
      - IRCT_DB_CONNECTION_USER=${IRCT_DB_CONNECTION_USER}
      - IRCTMYSQLPASS=${IRCTMYSQLPASS}
      - IRCT_SECURITY_SERVICE=${IRCT_SECURITY_SERVICE}
    restart: always
    networks:
      - i2b2-net
      - nhanes-net
    expose:
      - 8080

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${IRCTMYSQLPASS}
      - MYSQL_DATABASE=irct
    restart: always
    expose:
      - 3306
    networks:
      - nhanes-net

  irct-init:
    image: dtr.avl.dbmi.hms.harvard.edu/dbmi/irct-init:${irct_init_version}
    depends_on:
      - mysql
      - irct
    environment:
      - IRCT_RESOURCE_NAME=${APPLICATION_NAME}
      - IRCTMYSQLADDRESS=${IRCTMYSQLADDRESS}
      - IRCT_DB_PORT=${IRCT_DB_PORT}
      - IRCT_DB_CONNECTION_USER=${IRCT_DB_CONNECTION_USER}
      - IRCTMYSQLPASS=${IRCTMYSQLPASS}
      - SCIDB_HOST=${SCIDB_HOST}
      - SCIDB_USER=${SCIDB_USER}
      - SCIDB_PASSWORD=${SCIDB_PASSWORD}
    restart: on-failure:10
    networks:
      - nhanes-net

networks:
    nhanes-net:
        external:
            name: projects_nhanes-net
    i2b2-net:
        external:
            name: projects_i2b2-net
